# Dependencies
markdown: kramdown
highlighter: rouge
kramdown:
  auto_ids: true
sass:
  style: compressed

# Permalinks
#permalink: /:year/:month/:title
permalink: /:categories/:year/:month/:day/:title

# Server
source: .
destination: ./_gh_pages
port: 9001
encoding: UTF-8
exclude: [.git, .github, assets/bootstrap-4.0.0-beta/assets/scss/, build, js, node_modules, nuget, assets/bootstrap-4.0.0-beta/scss, vendor, bower.json, composer.json, Gemfile, Gemfile.lock, Gruntfile.js, package.js, package.json, package-lock.json, sache.json]

plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-last-modified-at

# Social
title: STAR Platform
description:
authors: Samsung Research

# Custom vars
cdn:
  # See https://www.srihash.org for info on how to generate the hashes
  css:            https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css
  css_hash:       "sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ"
  js:             https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js
  js_hash:        "sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn"
  jquery:         https://code.jquery.com/jquery-3.2.1.slim.min.js
  jquery_hash:    "sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
  popper:         https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js
  popper_hash:    "sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4"